ques one

In [ ]:
# takes type and then the actual value to be printed finally then converts accordingly and returns it
def convertLength(x,type):
  if (type=="meters"):
    result=x*3.28
  elif(type=="feet"):
    result=x/3.28
  return result

# takes weight and the type and converts accordingly and returns it
def convertWeight(x,type):
  if (type=="kilograms"):
    result=x*2.20
  elif(type=="pounds"):
    result=x/2.20
  return result

# takes volume and the type and converts accordingly and returns it
def convertVolume(x,type):
  if (type=="liters"):
    result=x*3.78
  elif(type=="gallons"):
    result=x/3.78
  return result

In [ ]:
conversion=input("Enter the type of conversion: length, weight, volume")
a=input("Enter the value to be converted: ")
try:
    a=int(a)
except:
    print("Invalid input")
type=input("Enter the type of value your entered: meters,feet,kilograms,pounds,liters,gallons")
match conversion:
  case "length":
    print(convertLength(a,type))
  case "weight":
    print(convertWeight(a,type))
  case "volume":
    print(convertVolume(a,type))


Enter the type of conversion: length, weight, volumelength
Enter the value to be converted: 5
Enter the type of value your entered: meters,feet,kilograms,pounds,liters,gallonsmeters
16.4


ques 2

In [ ]:
def sum(x):
  # takes a parameter list and provides the sum of the elements of list
  result=0
  for x in x:
    result+=x
  return result

def average(x):
  # takes a parameter list and returns the average of the elements
  result=0
  for x in x:
    sum+=x
  result=sum/len(x)
  return result

def maximum(x):
  # takes a parameter list and returns the maximum of the elements
  return max(x)

def minimum(x):
  # takes a parameter list and returns the maximum of the elements
  return min(x)


In [ ]:
a=input("enter list separated by spaces")
try:
  list=[int(x) for x in a if x.isnumeric()]
except:
  print("Enter valid numbers")
operation=input("Enter operation: sum, average,maximum,minimum")
match operation:
  case "sum":
    print(sum(list))
  case "average":
    print(average(list))
  case "maximum":
    print(maximum(list))
  case "minimum":
    print(minimum(list))


enter list separated by spaces1 2 3 4 5
Enter operation: sum, average,maximum,minimumsum
15


ques 3

In [ ]:
def extract_every_other(lst):
  new_list=[x for index,x in enumerate(lst) if index%2==0]
  return new_list

print(extract_every_other([1,2,3,4,5,6]))

[1, 3, 5]


ques 4

In [ ]:
def get_sublist(lst,start,end):
  new_list=lst[start:end+1]
  return new_list

print(get_sublist([1,2,3,4,5,6],2,4))

[3, 4, 5]


ques5

In [ ]:
def reverse_list(lst):
  new_list=lst[::-1]
  return new_list

print(reverse_list([1,2,3,4,5,6]))

[6, 5, 4, 3, 2, 1]


ques6

In [ ]:
def remove_first_last(lst):
  new_list=lst[1:len(lst)-1]
  return new_list

print(remove_first_last([1,2,3,4,5]))

[2, 3, 4]


ques7

In [ ]:
def get_first_n(lst,n):
  new_list=lst[:n]
  return new_list

print(get_first_n([1,2,3,4,5],3))

[1, 2, 3]


ques 8

In [ ]:
def get_last_n(lst,n):
  new_list=lst[len(lst)-n:]
  return new_list

print(get_last_n([1,2,3,4,5],2))

[4, 5]


ques 9

In [ ]:
def reverse_skip(lst):
  new_list=lst[::-1]
  new_list=new_list[1::2]
  return new_list

print(reverse_skip([1,2,3,4,5,6]))

[5, 3, 1]


ques 10

In [ ]:
def flatten(lst):
  new_list=[]
  for x in lst:
    for y in x:
      new_list.append(y)
  return new_list

print(flatten([[1,2,3],[4,5,6]]))


[1, 2, 3, 4, 5, 6]


ques 11

In [ ]:
def access_nested_element(lst,indices):
  for index in indices:
    lst=lst[index]
  return lst

print(access_nested_element([[1,2,3],[4,5,6],[7,8,9]],[1,2]))


6


ques12

In [ ]:
def sum_nested(lst):
  sum=0
  for x in lst:
    if(type(x)==list):
      for y in x:
        if(type(y)==list):
          for z in y:
            sum+=z
        else:
          sum+=y
    else:
      sum+=x
  return sum

print(sum_nested([[1, 2], [3, [4, 5]], 6]))

21


ques13

In [ ]:
def remove_element(lst,elem):
  for x in lst:
    for y in x:
      if(y==elem):
        x.remove(y)
  return lst

print(remove_element([[1, 2], [3, 2], [4, 5]],2))

[[1], [3], [4, 5]]


ques14

In [ ]:
def find_max(lst):
  max=0
  for x in lst:
    if(type(x)==list):
      for y in x:
        if(type(y)==list):
          for z in y:
            if(z>max):
              max=z
        else:
          if(y>max):
            max=y
    else:
      if(x>max):
        max=x
  return max

print(find_max([[1, 2], [3, [4, 5]], 6]))

6


ques 15

In [ ]:
def count_occurences(lst,elem):
  count=0
  for x in lst:
    for y in x:
      if(y==elem):
        count+=1
  return count

print(count_occurences([[1, 2], [3, 2], [4, 2]],2))

3


ques16

In [ ]:
def deep_flatten(lst):
  new_list=[]
  for x in lst:
    if(type(x)==list):
      for y in x:
        if(type(y)==list):
          for z in y:
            new_list.append(z)
        else:
          new_list.append(y)
    else:
      new_list.append(x)

  return new_list

print(deep_flatten([[1, 2], [3, [4, 5]], 6]))

[1, 2, 3, 4, 5, 6]


ques 17

In [ ]:
def average_nested(lst):
  avg=0
  sum=0
  length=0
  for x in lst:
    for y in x:
      sum+=y
      length+=1
  avg=sum/length
  return avg

print(average_nested([[1, 2], [3, 4], [5, 6]]))

3.5


ques 18

In [ ]:
import numpy as np

In [ ]:
empty_arr=np.empty(2)
one_arr=np.ones((4,2))
full_arr=np.full((2,3),5)
zerolikearr=np.zeros_like(one_arr)
onelikearr=np.ones_like(one_arr)
lstarr=np.array([1,2,3,4])
print(empty_arr)
print(one_arr)
print(full_arr)
print(zerolikearr)
print(onelikearr)
print(lstarr)

[5.73021895e-300 6.53279850e-310]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[5 5 5]
 [5 5 5]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[1 2 3 4]


ques 19

In [ ]:
range_arr=np.arange(10,49)
matrix=np.arange(0,9).reshape((3,3))
eye_matrix=np.eye(3)
rand=np.random.random((3,3))
mean=rand.mean()
rand1=np.random.random((10,10))
max=rand1.max()
min=rand1.min()
zeroarr=np.zeros((10,10))
zeroarr[6]=1
arr=[1,2,0,0,4,0]
reversearr=arr[::-1]
arrborder=np.zeros((3,3))
arrborder[0,:]=1
arrborder[:,0]=1
arrborder[:,-1]=1
arrborder[-1,:]=1
checkerboard=np.zeros((8,8))
checkerboard[1::2,::2]=1
checkerboard[::2,1::2]=1
print(range_arr)
print(matrix)
print(eye_matrix)
print(rand)
print(mean)
print(rand1)
print(max)
print(min)
print(zeroarr)
print(reversearr)
print(arrborder)
print(checkerboard)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.52409022 0.51777718 0.31438889]
 [0.85993692 0.4473734  0.60655443]
 [0.48406256 0.76237045 0.95992559]]
0.6084977382366079
[[7.60221843e-01 2.42220142e-01 2.13574424e-01 5.34280109e-01
  1.20500402e-01 8.64782862e-03 8.87038662e-01 9.74775122e-02
  9.24619698e-01 6.20195144e-01]
 [6.26596188e-01 7.13842351e-01 7.28054764e-01 4.76756697e-01
  4.11731980e-01 9.53215902e-01 6.23431682e-01 6.43117965e-02
  1.47375457e-01 9.48350470e-05]
 [8.70932569e-01 4.64361713e-01 5.46080044e-01 5.72845581e-01
  4.13760525e-01 3.94537721e-01 1.75650600e-01 6.18880905e-01
  4.79390050e-03 8.46199298e-01]
 [9.39209599e-03 5.84891630e-01 4.66945379e-01 8.42023213e-01
  7.71400596e-01 8.54348466e-01 6.20594613e-01 6.51526752e-01
  9.38648457e-01 6.21524147e-01]
 [4.16077007e-01 6.70063756e-02 1.03380827e-01 9.10534847e-

ques20

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
sum=np.add(x,y)
sub=np.subtract(x,y)
multiply=np.multiply(x,y)
square=np.square(x)
vdotw=np.dot(v,w)
xdotv=np.dot(x,v)
xdoty=np.dot(x,y)
rowconcat=np.concatenate((x,y),axis=0)
columnconcat=np.concatenate((x,y),axis=1)
print(sum)
print(sub)
print(multiply)
print(square)
print(vdotw)
print(xdotv)
print(xdoty)
print(rowconcat)
print(columnconcat)

[[ 6  8]
 [10 13]]
[[-4 -4]
 [-4 -3]]
[[ 5 12]
 [21 40]]
[[ 1  4]
 [ 9 25]]
219
[29 77]
[[19 22]
 [50 58]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 5 7 8]]


ques21

In [ ]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
ainverse=np.linalg.inv(A)
eye=A@ainverse
AB=np.matmul(A,B)
BA=np.matmul(B,A)
At=np.transpose(A)
Bt=np.transpose(B)
ABt=np.transpose(AB)
BtAt=np.matmul(Bt,At)
print(eye)
print(AB)
print(BA)
print(ABt)
print(BtAt)

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
[[23 13]
 [51 29]]
[[36 44]
 [13 16]]
[[23 51]
 [13 29]]
[[23 51]
 [13 29]]
